version: 2.0
jobs:
  build:
    branches:
      only:
        - master
        - /rc-.*/
    docker:
      - image: circleci/node:7.10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: npm install
      - run: npm test
